language: python
python:
  - "3.6"
cache: pip
install:
  - pip install -e .
  - pip install -r requirements.txt
script:
  - pytest -sv deauthorized/tests.py

env:
  - OPENID_CLIENT_ID=test_client_id OPENID_CLIENT_SECRET=test_secret_id OPENID_ISSUER=https://srv.qryp.to/op
